[package]
name = "mabez_watch"
version = "0.0.1"
authors = ["Scott Mabin <mabezdev@gmail.com>"]
description = "A 'Smart' watch"
keywords = ["arm", "cortex-m", "smartwatch"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mabezdev/mabez_watch_rust"

[dependencies]
nb = "0.1.1"
cortex-m = "0.5.6"
cortex-m-rt = "0.5.3"
cortex-m-semihosting = "0.3.0"
cortex-m-rtfm = { git = "https://github.com/mabezdev/cortex-m-rtfm" }
# cortex-m-rtfm = { path = "../../util/cortex-m-rtfm" }
heapless = "0.3.7"
panic-semihosting = "0.3.0"
embedded-graphics = "0.3.0"

[dependencies.ssd1351]
version = "0.1.0"
features = ["embedded-graphics"]

[dependencies.stm32l432xx-hal]
version = "0.2.2"
# git = "https://github.com/mabezdev/stm32l432xx-hal"
# branch = "dma-circ-fixes"
# path = "../../hal/stm32l432xx-hal"

[dependencies.stm32l4]
version = "0.2.1"
features = ["stm32l4x2", "rt"]

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
lto = true
debug = true
