
[workspace]
members = ["kernel", "kernel-stm32l4", "kernel-esp32s3"]

[profile.dev]
codegen-units = 1
incremental = false
opt-level = 'z' # 0 or 1 for debug

[profile.release]
codegen-units = 1
lto = true
debug = true
